### ISSUE TITLE
App crashed when reopening it from the launcher

### ISSUE THREAD

**Issue by rayworks** [PureMVC/purmevc-java-demo-android-employeeadmin#1]
Attached log 
`Process: org.puremvc.java.demos.android.employeeadmin, PID: 23888
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.puremvc.java.demos.android.employeeadmin/org.puremvc.java.demos.android.employeeadmin.view.components.UserListActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.ArrayList org.puremvc.java.demos.android.employeeadmin.view.interfaces.IUserListActivity.getUsers()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3388)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3527)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2123)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7710)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.ArrayList org.puremvc.java.demos.android.employeeadmin.view.interfaces.IUserListActivity.getUsers()' on a null object reference
        at org.puremvc.java.demos.android.employeeadmin.view.components.UserListActivity.onCreate(UserListActivity.java:39)
        at android.app.Activity.performCreate(Activity.java:7820)
        at android.app.Activity.performCreate(Activity.java:7809)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1318)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3363)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3527) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2123) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7710)`

**Comment by saadshams** [comment]
Updated with a fix, let me know for any other issues. By the way [Kotlin Demo](https://github.com/PureMVC/puremvc-kotlin-demo-android-employeeadmin) is frequently updated and is more aligned with how Android works, do check it out.
